dartalla/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('user.urls')),
    path('', include('dashboard.urls')),
    path('', include('person.urls')),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import DashboardView

app_name = "dashboard"

urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard")
]

person/urls.py
from django.urls import path

from person.views import ListPersonView

app_name = "person"

urlpatterns = [
    path("person/", ListPersonView.as_view(), name="list")
]

user/urls.py
from django.urls import path

urlpatterns = [
    
]

cpf/models.py
from django.db import models

# Create your models here.

person/models.py
from django.db import models
from django.utils.translation import gettext as _


class Person(models.Model):
    class Meta:
        verbose_name = _("Person")
        verbose_name_plural = _("Persons")

    cpf = models.CharField(verbose_name=_("CPF"), max_length=11)

    name = models.CharField(verbose_name=_("Nome"), max_length=255)

    social_name = models.CharField(verbose_name=_("Nome Social"), max_length=255)

    subscription_status = models.CharField(
        verbose_name=_("Situação Cadastral"),
        max_length=255
    )

    stranger_resident = models.CharField(
        verbose_name=_("Residente no Exterior"),
        max_length=1
    )

    resident_country_code = models.CharField(
        verbose_name=_("Código País"),
        max_length=100
    )

    resident_country = models.CharField(
        verbose_name=_("Nome do País"),
        max_length=255
    )

    mother = models.CharField(
        verbose_name=_("Nome da Mãe"),
        max_length=255
    )

    birth_date = models.DateField(
        verbose_name=_("Data de Nasc"),
        null=True,
        blank=True
    )

    birth_country = models.CharField(
        verbose_name=_("Cód. País de Nasc."),
        max_length=3
    )

    birth_country_code = models.CharField(
        verbose_name=_("País de Nasc."),
        max_length=255
    )

    birth_province_code = models.CharField(
        verbose_name=_("Cód. Estado de Nasc."),
        max_length=3
    )

    birth_city = models.CharField(
        verbose_name=_("Natural de"),
        max_length=255
    )

    birth_city_code = models.CharField(
        verbose_name=_("Cód. Cidade de Nasc."),
        max_length=3
    )

    gender = models.IntegerField(
        verbose_name=_("Sexo"),
    )

    occupation_origin_code = models.CharField(
        verbose_name=_("Cód. da Natureza da Ocupação"),
        max_length=50
    )

    occupation_origin = models.CharField(
        verbose_name=_("Natureza da Ocupação"),
        max_length=255
    )

    main_occupation_code = models.CharField(
        verbose_name=_("Cód. Ocupação Principal"),
        max_length=50
    )

    main_occupation = models.CharField(
        verbose_name=_("Ocupação Principal"),
        max_length=255
    )

    occupation_current_year = models.CharField(
        verbose_name=_("Exercício da Ocupação"),
        max_length=50
    )

    administrative_unit = models.CharField(
        verbose_name=_("Unidade Administrativa"),
        max_length=255
    )

    administrative_unit_code = models.CharField(
        verbose_name=_("Cod. U. Administrativa"),
        max_length=10
    )

    address_type = models.CharField(
        verbose_name=_("Tipo de Logradouro"),
        max_length=255
    )

    address = models.CharField(
        verbose_name=_("Endereço"),
        max_length=255
    )

    address_number = models.CharField(
        verbose_name=_("Número"),
        max_length=50
    )

    address_complement = models.CharField(
        verbose_name=_("Complemento"),
        max_length=255
    )

    address_neighbor = models.CharField(
        verbose_name=_("Bairro"),
        max_length=255
    )

    address_zip = models.IntegerField(
        verbose_name=_("CEP"),
    )

    province_code = models.CharField(
        verbose_name=_("UF"),
        max_length=2
    )

    city_code = models.CharField(
        verbose_name=_("Código Município"),
        max_length=10
    )

    city = models.CharField(
        verbose_name=_("Município"),
        max_length=255
    )

    phone_code = models.CharField(
        verbose_name=_("DDD"),
        max_length=3
    )

    phone = models.CharField(
        verbose_name=_("Telefone"),
        max_length=16
    )

    death_date = models.CharField(
        verbose_name=_("Ano do Óbito"),
        max_length=4
    )

    stranger = models.CharField(
        verbose_name=_("Estrangeiro"),
        max_length=1
    )

    updated_at = models.DateField(
        verbose_name=_("Data de Atualização"),
    )

    created_at = models.DateField(
        verbose_name=_("Data de Inscrição"),
    )

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

cpf/views.py
from django.shortcuts import render

# Create your views here.

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class DashboardView(View):
    template_name = "index.html"

    def get(self, request):
        return render(request, self.template_name)

person/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from cpf.cpf import CpfMixin
from person.models import Person


class ListPersonView(LoginRequiredMixin, CpfMixin, ListView):
    model = Person

    def get_context_data(self, *, object_list=None, **kwargs):
        cx = super(ListPersonView, self).get_context_data(**kwargs)
        cx.update({"response": self.get_token()})
        return cx

user/views.py
from django.shortcuts import render

dashboard/templates/includes/base.html
{% load static i18n %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">

        <title>{% block title %}{{ title }} {% endblock %} | Dartalla</title>
    </head>
    <body class="bg-dark text-light">
        {% include 'includes/header.html' %}

        <div class="container-fluid">
            {% block content %} {% endblock %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
    </body>
</html>

dashboard/templates/includes/header.html
{% load static i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand h1 mb-0" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if "/" == request.path %}active{% endif %}" aria-current="page" href="{% url 'dashboard:dashboard' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if "/person/" == request.path %}active{% endif %}" aria-current="page"
                       href="{% url 'person:list' %}">{% trans 'Pessoas' %}</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-expanded="false">
                            <img src="{% static 'icons/person-circle.svg' %}" class="m-0 p-0 my-auto" width="24" height="24"
                             alt="User"/>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <li><a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Sign Out' %}</a></li>
                        </ul>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

dashboard/templates/index.html
{% extends 'includes/base.html' %}
{% load static i18n %}

{% block title %} {% trans 'Dashboard' %} {% endblock %}

{% block content %}

{% endblock %}

person/templates/person/person_list.html
{% extends 'includes/base.html' %}

{% block content %}
{{ response.text|safe }}
{% endblock %}

user/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">

        <title>{% block title %}{{ title }}{% endblock %}</title>
        {% block extra_style %} {% endblock extra_style %}
    </head>
    <body class="bg-light">
        {% block navbar %} {% endblock navbar %}

        {% block breadcrumb %} {% endblock breadcrumb %}

        {% block content %} {% endblock content %}

        {% block footer %} {% endblock footer %}

        {% block script %}
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
            <script src="{% static 'js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
        {% endblock script %}
        {% block extra_script %} {% endblock extra_script %}
    </body>
</html>